<a href="https://colab.research.google.com/github/kingr0009/Gcolab-python/blob/main/dd_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Numpy Arrays
import numpy as np
my_list = [1,2,3,4]
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [3]:
second_list =[5,6,7,8]
two_d_array =np.array([my_list,second_list])
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
two_d_array.shape #checks matrix dimension

(2, 4)

In [6]:
two_d_array.size

8

In [7]:
two_d_array.dtype

dtype('int64')

In [9]:
np.identity(n=5) #creates a square 2d array with '1's across diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros(shape=(2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#indexing and slicing
one_d_array = np.array([1,2,3,4,5,6,7])
one_d_array[4]

5

In [14]:
#same operations as before on lists
one_d_array[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [15]:
#create a new 2d array
two_d_array = np.array([one_d_array, one_d_array +6 , one_d_array +12])
print(two_d_array)

[[ 1  2  3  4  5  6  7]
 [ 7  8  9 10 11 12 13]
 [13 14 15 16 17 18 19]]


In [16]:
#get elemenet at row 1, column index 4
two_d_array[1,4] #starts from row 0

11

In [21]:
np.reshape(a=two_d_array, newshape=(7,3)) #reshaping our matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  7,  8],
       [ 9, 10, 11],
       [12, 13, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [24]:
#sorts in order                        #c is correct order, #f is fortran style order
np.ravel(a=two_d_array, order='c')

array([ 1,  2,  3,  4,  5,  6,  7,  7,  8,  9, 10, 11, 12, 13, 13, 14, 15,
       16, 17, 18, 19])

In [26]:
# another similar function
two_d_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  7,  8,  9, 10, 11, 12, 13, 13, 14, 15,
       16, 17, 18, 19])

In [30]:
#flip array

q=np.flip(two_d_array)
w=np.fliplr(two_d_array)
e=np.flipud(two_d_array)
print(q)

print(w)

print(e)

[[19 18 17 16 15 14 13]
 [13 12 11 10  9  8  7]
 [ 7  6  5  4  3  2  1]]
[[ 7  6  5  4  3  2  1]
 [13 12 11 10  9  8  7]
 [19 18 17 16 15 14 13]]
[[13 14 15 16 17 18 19]
 [ 7  8  9 10 11 12 13]
 [ 1  2  3  4  5  6  7]]


In [36]:
np.rot90(two_d_array, k=1) #rotate matrix

array([[ 7, 13, 19],
       [ 6, 12, 18],
       [ 5, 11, 17],
       [ 4, 10, 16],
       [ 3,  9, 15],
       [ 2,  8, 14],
       [ 1,  7, 13]])

In [37]:
#shift elements in array
np.roll(two_d_array, shift=1, axis=0)

array([[13, 14, 15, 16, 17, 18, 19],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [40]:
array_to_join = np.array([[10,11,12,13,14,15,16]])
np.concatenate((two_d_array, array_to_join), axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 11, 12, 13],
       [13, 14, 15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14, 15, 16]])

In [41]:
#array math ops
two_d_array + two_d_array

array([[ 2,  4,  6,  8, 10, 12, 14],
       [14, 16, 18, 20, 22, 24, 26],
       [26, 28, 30, 32, 34, 36, 38]])

In [42]:
two_d_array * two_d_array

array([[  1,   4,   9,  16,  25,  36,  49],
       [ 49,  64,  81, 100, 121, 144, 169],
       [169, 196, 225, 256, 289, 324, 361]])

In [43]:
two_d_array - two_d_array

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [44]:
two_d_array -100

array([[-99, -98, -97, -96, -95, -94, -93],
       [-93, -92, -91, -90, -89, -88, -87],
       [-87, -86, -85, -84, -83, -82, -81]])

In [46]:
np.mean(two_d_array, axis=1)


array([ 4., 10., 16.])

In [49]:
g=np.std(two_d_array, axis=1)
h=np.std(two_d_array)
print(g)
print(h)

[2. 2. 2.]
5.291502622129181


In [50]:
#axis = 1 ------- ROWS
#axis = 0 ------- Columns

In [51]:
np.sum(two_d_array, axis=0)

array([21, 24, 27, 30, 33, 36, 39])

In [52]:
np.log10(two_d_array)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
        0.77815125, 0.84509804],
       [0.84509804, 0.90308999, 0.95424251, 1.        , 1.04139269,
        1.07918125, 1.11394335],
       [1.11394335, 1.14612804, 1.17609126, 1.20411998, 1.23044892,
        1.25527251, 1.2787536 ]])

In [53]:
np.sqrt(two_d_array)
#

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162, 3.60555128],
       [3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
        4.24264069, 4.35889894]])

In [54]:
np.dot(two_d_array, two_d_array.T) #multiply with its ranspose

array([[ 140,  308,  476],
       [ 308,  728, 1148],
       [ 476, 1148, 1820]])